name: Sync README to docs

on:
  push:
    branches: [ main ]
    paths:
      - README.md

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Copy README to docs/index.md
        run: |
          mkdir -p docs
          cp README.md docs/index.md
      - name: Commit changes
        run: |
          if ! git diff --quiet; then
            git config user.name "github-actions[bot]"
            # Automated via GitHub Actions bot <https://github.com/apps/github-actions>
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add docs/index.md
            git commit -m "docs: sync README to docs/index.md"
            git push
          fi
