name: Sync README to docs

on:
  push:
    branches: [ main ]
    paths: [ README.md ]

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Copy README to docs/index.md (rewrite image paths)
        run: |
          mkdir -p docs
          cp README.md docs/index.md
          # Rewrite relative image paths (src="images/...) to use site.baseurl
          sed -i 's#src="images/#src="{{ site.baseurl }}/images/#g' docs/index.md

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changes
        run: |
          git add docs/index.md
          if ! git diff --staged --quiet; then
            git commit -m "docs: sync README to docs/index.md"
            git push
          else
            echo "No changes to commit"
          fi
